---
default_stages: [pre-commit]

default_install_hook_types: [pre-commit, commit-msg]

ci:
  autoupdate_commit_msg: 'pre-commit: autoupdate hooks'
  autofix_prs: false

repos:
  - repo: https://github.com/talos-systems/conform
    rev: v0.1.0-alpha.30
    hooks:
      - id: conform
        stages:
          - commit-msg
