gEfiMdeModulePkgTokenSpaceGuid.PcdBrowserFieldBackgroundHighlightColor|0x60 
gEfiMdeModulePkgTokenSpaceGuid.PcdBrowserFieldTextHighlightColor|0x0F
gEfiMdeModulePkgTokenSpaceGuid.PcdBrowserTitleBackgroundColor|0x60
gEfiMdeModulePkgTokenSpaceGuid.PcdBrowserTitleTextColor|0x0F
gEfiMdeModulePkgTokenSpaceGuid.PcdBrowserPopupBackgroundColor|0x60
gEfiMdeModulePkgTokenSpaceGuid.PcdBrowserPopupTextColor|0x0F
gEfiMdeModulePkgTokenSpaceGuid.PcdBrowserPopupInverseTextColor|0x30
gEfiMdeModulePkgTokenSpaceGuid.PcdBrowserPopupInverseBackgroundColor|0x06
gEfiMdeModulePkgTokenSpaceGuid.PcdBrowserHelpTextColor|0x07
gEfiMdeModulePkgTokenSpaceGuid.PcdBrowserHelpBackgroundColor|0x30
gEfiMdeModulePkgTokenSpaceGuid.PcdBrowserInfoTextColor|0x06
gEfiMdeModulePkgTokenSpaceGuid.PcdBrowserInfoBackgroundColor|0x30
gEfiMdeModulePkgTokenSpaceGuid.PcdBrowserFieldTextColor|0x06
gEfiMdeModulePkgTokenSpaceGuid.PcdBrowserFieldBackgroundColor|0x30
gEfiMdeModulePkgTokenSpaceGuid.PcdBrowserSubtitleTextColor|0x02
gEfiMdeModulePkgTokenSpaceGuid.PcdBrowserBannerBackgroundColor|0x60
gEfiMdeModulePkgTokenSpaceGuid.PcdBrowserBannerTextColor|0x0F
gEfiMdeModulePkgTokenSpaceGuid.PcdBrowserKeyHelpTextColor|0x02
gEfiMdeModulePkgTokenSpaceGuid.PcdBrowserKeyHelpBackgroundColor|0x60
gEfiMdeModulePkgTokenSpaceGuid.PcdBrowserPickListTextColor|0x06
gEfiMdeModulePkgTokenSpaceGuid.PcdBrowserPickListBackgroundColor|0x30
gEfiMdeModulePkgTokenSpaceGuid.PcdBrowserArrowTextColor|0x0F
gEfiMdeModulePkgTokenSpaceGuid.PcdBrowserArrowBackgroundColor|0x60
gEfiMdeModulePkgTokenSpaceGuid.PcdBrowserFieldGrayedTestColor|0x07

gEfiMdeModulePkgTokenSpaceGuid.PcdGraphicsConsoleColorPaletteBlack      | { 0x00, 0x00, 0x00, 0x00 }    # 0 Plain black
gEfiMdeModulePkgTokenSpaceGuid.PcdGraphicsConsoleColorPaletteLightBlue  | { 0x00, 0x00, 0x00, 0x98 }    # 1 Dark green
gEfiMdeModulePkgTokenSpaceGuid.PcdGraphicsConsoleColorPaletteLightGreen | { 0x00, 0x38, 0xD4, 0x30 }    # 2 Dasharo green
gEfiMdeModulePkgTokenSpaceGuid.PcdGraphicsConsoleColorPaletteLightCyan  | { 0x00, 0xFF, 0xFF, 0xFF }    # 3 White
gEfiMdeModulePkgTokenSpaceGuid.PcdGraphicsConsoleColorPaletteLightRed   | { 0x00, 0x98, 0x00, 0x00 }    # 4 Red
gEfiMdeModulePkgTokenSpaceGuid.PcdGraphicsConsoleColorPaletteMagenta    | { 0x00, 0x98, 0x00, 0x98 }    # 5 Magenta
gEfiMdeModulePkgTokenSpaceGuid.PcdGraphicsConsoleColorPaletteBrown      | { 0x00, 0x29, 0x36, 0x3b }    # 6 Dasharo grey
gEfiMdeModulePkgTokenSpaceGuid.PcdGraphicsConsoleColorPaletteLightGray  | { 0x00, 0x80, 0x80, 0x80 }    # 7 Light grey

gEfiMdeModulePkgTokenSpaceGuid.PcdGraphicsConsoleColorPaletteDarkGray   | { 0x00, 0x30, 0x30, 0x30 }    # 00 Dark grey
gEfiMdeModulePkgTokenSpaceGuid.PcdGraphicsConsoleColorPaletteBlue       | { 0x00, 0x00, 0x00, 0xFF }    # 10 Blue
gEfiMdeModulePkgTokenSpaceGuid.PcdGraphicsConsoleColorPaletteLime       | { 0x00, 0x00, 0xFF, 0x00 }    # 20 Green
gEfiMdeModulePkgTokenSpaceGuid.PcdGraphicsConsoleColorPaletteCyan       | { 0x00, 0xFF, 0xFF, 0x00 }    # 30 Cyan
gEfiMdeModulePkgTokenSpaceGuid.PcdGraphicsConsoleColorPaletteRed        | { 0x00, 0xFF, 0x00, 0x00 }    # 40 Red
gEfiMdeModulePkgTokenSpaceGuid.PcdGraphicsConsoleColorPaletteFuchsia    | { 0x00, 0xFF, 0x00, 0xFF }    # 50 Fuchsia
gEfiMdeModulePkgTokenSpaceGuid.PcdGraphicsConsoleColorPaletteYellow     | { 0x00, 0xFF, 0xFF, 0x00 }    # 60 Yellow
gEfiMdeModulePkgTokenSpaceGuid.PcdGraphicsConsoleColorPaletteWhite      | { 0x00, 0xFF, 0xFF, 0xFF }    # 70 White