## @file
# Dasharo DSC include file for [Components*] section.
#
# This file can be included to the [Components*] section(s) of a platform DSC file
# by using "!include DasharoModulePkg/DasharoModuleComponents.dsc.inc" to specify the INF files.
#
# Copyright (c) 2022, 3mdeb Sp. z o.o. All rights reserved.<BR>
# SPDX-License-Identifier: BSD-2-Clause
#
##

  DasharoModulePkg/Library/DasharoSystemFeaturesUiLib/DasharoSystemFeaturesUiLib.inf
  DasharoModulePkg/UserAuthenticationDxe/UserAuthenticationDxe.inf
